default['mysql']['bind_address']  				= '0.0.0.0'
default['mysql]'['port']          				= '3306'
default['mysql]'['socket']        				= '/var/run/mysqld/mysqld.sock'

default['mysql]'['tokudb_data_dir']				= '/var/lib/mysql'
default['mysql']['tokudb_install_dir'] 			= '/opt/tokutek/mysql'
default['mysql']['user'] 						= 'mysql'
default['mysql]'['basedir']						= '/usr/local/mysql'
default['mysql']['tmpdir']						= '/tmp'
default['mysql]'['datadir']						= '/mysqldata/datafiles'

default['mysql']['tunable']['open_files_limit'] = '50005'
default['mysql']['tunable']['table_open_cache'] = '5000'
default['mysql']['tunable']['skip_character_set_client_handshake'] = false
default['mysql']['tunable']['character_set_server'] = 'utf8'
default['mysql']['tunable']['character_set_filesystem']	 = 'utf8'
default['mysql']['tunable']['slow_query_log_file']	= '/mnt/var/log/mysql/log-slow-queries.log'
default['mysql']['tunable']['slow_query_log']		= '1'
default['mysql']['tunable']['long_query_time']		= '2'

default['mysql']['tunable']['bulk_insert_buffer_size']  = '32M'
default['mysql']['tunable'][['max_connections'] 	    = '10000'
default['mysql']['tunable'][['max_connect_errors'] 	    = '10000'
default['mysql']['tunable']['innodb_buffer_pool_size']  = '128M'

default['mysql']['tunable']['max_allowed_packet']   = '16M'
default['mysql']['tunable']['thread_cache_size']    = '8'
default['mysql']['tunable']['thread_concurrency']   = '10'
default['mysql']['tunable']['thread_stack']         = '192K'
default['mysql']['tunable']['key_buffer']         	= '16M'
default['mysql']['tunable']['query_cache_limit']	= '1M'
default['mysql']['tunable']['query_cache_size'] 	= '0'
default['mysql']['log_error'] 						= '/mnt/var/log/mysql/error.log'
default['mysql']['tunable']['server_id'] 	        = '2'
default['mysql']['tunable']['log_bin']              = '/mnt/log/mysql/mysql-bin.log'
default['mysql']['tunable']['binlog_format']    	= 'ROW'
default['mysql']['tunable']['expire_logs_days']     = '4'
default['mysql']['tunable']['max_binlog_size']      = '1G'
default['mysql']['tunable']['sync_binlog']        	= '0'
default['mysql']['tunable']['thread_pool_size'] 	 = '500'
default['mysql']['tunable']['transaction_isolation'] = 'READ-COMMIT'
default['mysql']['tunable']['event_scheduler'] 		  = 'READ-OFF'
default['mysql']['tunable']['innodb_buffer_pool_size']	= '1G'
default['mysql']['tunable']['innodb_flush_method']	= 'O_DIRECT'
default['mysql']['tunable']['innodb_log_file_size']	= '256M'
default['mysql']['tunable']['innodb_log_buffer_size']	= '4M'
default['mysql']['tunable']['innodb_flush_log_at_trx_commit']  = '2'
default['mysql']['tunable']['innodb_thread_concurrency']= '0'
default['mysql']['tunable']['innodb_io_capacity'] 	    = '200'
default['mysql']['tunable']['innodb_write_io_threads']	= '2'
default['mysql']['tunable']['innodb_read_io_threads']	= '4'

default['mysql']['tunable']['read_rnd_buffer_size'] = '32M'
default['mysql']['tunable']['max_heap_table_size']  = '128M'
default['mysql']['tunable']['tmp_table_size'] 		= '128M'
default['mysql']['tunable']['max_allowed_packet'] 	= '16M'
default['mysql']['tunable']['key_buffer_size']  	= '16M'
